// Generated by rstantools.  Do not edit by hand.

/*
    BayesGrowth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BayesGrowth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BayesGrowth.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_Ranef_VB_stan_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 42> locations_array__ =
  {" (found before start of program)",
  " (in 'Ranef_VB_stan_model', line 12, column 2 to column 21)",
  " (in 'Ranef_VB_stan_model', line 13, column 2 to column 18)",
  " (in 'Ranef_VB_stan_model', line 14, column 2 to column 10)",
  " (in 'Ranef_VB_stan_model', line 15, column 2 to column 29)",
  " (in 'Ranef_VB_stan_model', line 16, column 2 to column 25)",
  " (in 'Ranef_VB_stan_model', line 17, column 2 to column 17)",
  " (in 'Ranef_VB_stan_model', line 18, column 2 to column 28)",
  " (in 'Ranef_VB_stan_model', line 19, column 2 to column 24)",
  " (in 'Ranef_VB_stan_model', line 20, column 2 to column 25)",
  " (in 'Ranef_VB_stan_model', line 21, column 2 to column 22)",
  " (in 'Ranef_VB_stan_model', line 42, column 4 to column 22)",
  " (in 'Ranef_VB_stan_model', line 44, column 6 to column 155)",
  " (in 'Ranef_VB_stan_model', line 43, column 19 to line 45, column 5)",
  " (in 'Ranef_VB_stan_model', line 43, column 4 to line 45, column 5)",
  " (in 'Ranef_VB_stan_model', line 25, column 2 to column 41)",
  " (in 'Ranef_VB_stan_model', line 26, column 2 to column 28)",
  " (in 'Ranef_VB_stan_model', line 27, column 2 to column 39)",
  " (in 'Ranef_VB_stan_model', line 28, column 2 to column 38)",
  " (in 'Ranef_VB_stan_model', line 29, column 2 to column 27)",
  " (in 'Ranef_VB_stan_model', line 30, column 2 to column 30)",
  " (in 'Ranef_VB_stan_model', line 31, column 1 to column 37)",
  " (in 'Ranef_VB_stan_model', line 32, column 2 to column 34)",
  " (in 'Ranef_VB_stan_model', line 33, column 2 to column 35)",
  " (in 'Ranef_VB_stan_model', line 34, column 2 to column 32)",
  " (in 'Ranef_VB_stan_model', line 37, column 4 to column 150)",
  " (in 'Ranef_VB_stan_model', line 36, column 17 to line 38, column 3)",
  " (in 'Ranef_VB_stan_model', line 36, column 2 to line 38, column 3)",
  " (in 'Ranef_VB_stan_model', line 2, column 2 to column 17)",
  " (in 'Ranef_VB_stan_model', line 3, column 2 to column 17)",
  " (in 'Ranef_VB_stan_model', line 4, column 9 to column 10)",
  " (in 'Ranef_VB_stan_model', line 4, column 2 to column 16)",
  " (in 'Ranef_VB_stan_model', line 5, column 9 to column 10)",
  " (in 'Ranef_VB_stan_model', line 5, column 2 to column 19)",
  " (in 'Ranef_VB_stan_model', line 6, column 35 to column 36)",
  " (in 'Ranef_VB_stan_model', line 6, column 2 to column 38)",
  " (in 'Ranef_VB_stan_model', line 8, column 2 to column 19)",
  " (in 'Ranef_VB_stan_model', line 9, column 2 to column 31)",
  " (in 'Ranef_VB_stan_model', line 15, column 18 to column 19)",
  " (in 'Ranef_VB_stan_model', line 16, column 18 to column 19)",
  " (in 'Ranef_VB_stan_model', line 17, column 9 to column 10)",
  " (in 'Ranef_VB_stan_model', line 42, column 11 to column 12)"};
#include <stan_meta_header.hpp>
class model_Ranef_VB_stan_model final : public model_base_crtp<model_Ranef_VB_stan_model> {
private:
  int N;
  int J;
  Eigen::Matrix<double,-1,1> age_data__;
  Eigen::Matrix<double,-1,1> length_data__;
  std::vector<int> individual;
  Eigen::Matrix<double,-1,1> priors_data__;
  Eigen::Matrix<double,-1,1> priors_se_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> age{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> length{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> priors_se{nullptr, 0};
public:
  ~model_Ranef_VB_stan_model() {}
  model_Ranef_VB_stan_model(stan::io::var_context& context__, unsigned int
                            random_seed__ = 0, std::ostream*
                            pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_Ranef_VB_stan_model_namespace::model_Ranef_VB_stan_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 28;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 28;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 29;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("age", "N", N);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "age", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      age_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                     std::numeric_limits<double>::quiet_NaN());
      new (&age) Eigen::Map<Eigen::Matrix<double,-1,1>>(age_data__.data(), N);
      {
        std::vector<local_scalar_t__> age_flat__;
        current_statement__ = 31;
        age_flat__ = context__.vals_r("age");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 31;
          stan::model::assign(age, age_flat__[(pos__ - 1)],
            "assigning variable age", stan::model::index_uni(sym1__));
          current_statement__ = 31;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("length", "N", N);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "length", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      length_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                        std::numeric_limits<double>::quiet_NaN());
      new (&length)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(length_data__.data(), N);
      {
        std::vector<local_scalar_t__> length_flat__;
        current_statement__ = 33;
        length_flat__ = context__.vals_r("length");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 33;
          stan::model::assign(length, length_flat__[(pos__ - 1)],
            "assigning variable length", stan::model::index_uni(sym1__));
          current_statement__ = 33;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 34;
      stan::math::validate_non_negative_index("individual", "N", N);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "individual", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      individual = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 35;
      individual = context__.vals_i("individual");
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "individual",
        individual, 1);
      current_statement__ = 35;
      stan::math::check_less_or_equal(function__, "individual", individual, J);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "priors", "double",
        std::vector<size_t>{static_cast<size_t>(7)});
      priors_data__ = Eigen::Matrix<double,-1,1>::Constant(7,
                        std::numeric_limits<double>::quiet_NaN());
      new (&priors)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(priors_data__.data(), 7);
      {
        std::vector<local_scalar_t__> priors_flat__;
        current_statement__ = 36;
        priors_flat__ = context__.vals_r("priors");
        current_statement__ = 36;
        pos__ = 1;
        current_statement__ = 36;
        for (int sym1__ = 1; sym1__ <= 7; ++sym1__) {
          current_statement__ = 36;
          stan::model::assign(priors, priors_flat__[(pos__ - 1)],
            "assigning variable priors", stan::model::index_uni(sym1__));
          current_statement__ = 36;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 37;
      context__.validate_dims("data initialization", "priors_se", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      priors_se_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                           std::numeric_limits<double>::quiet_NaN());
      new (&priors_se)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(priors_se_data__.data(), 2);
      {
        std::vector<local_scalar_t__> priors_se_flat__;
        current_statement__ = 37;
        priors_se_flat__ = context__.vals_r("priors_se");
        current_statement__ = 37;
        pos__ = 1;
        current_statement__ = 37;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 37;
          stan::model::assign(priors_se, priors_se_flat__[(pos__ - 1)],
            "assigning variable priors_se", stan::model::index_uni(sym1__));
          current_statement__ = 37;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "priors_se", priors_se,
        0);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("L_inf_j", "J", J);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("K_j", "J", J);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("L0_j", "J", J);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + J + J + J + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_Ranef_VB_stan_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_Ranef_VB_stan_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ Linf = DUMMY_VAR__;
      current_statement__ = 1;
      Linf = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 2;
      k = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
            lp__);
      local_scalar_t__ L0 = DUMMY_VAR__;
      current_statement__ = 3;
      L0 = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__,-1,1> L_inf_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 4;
      L_inf_j = in__.template read_constrain_lb<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                  J);
      Eigen::Matrix<local_scalar_t__,-1,1> K_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 5;
      K_j = in__.template read_constrain_lb<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, J);
      Eigen::Matrix<local_scalar_t__,-1,1> L0_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 6;
      L0_j = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      local_scalar_t__ sigma_L_inf = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_L_inf = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      local_scalar_t__ sigma_K = DUMMY_VAR__;
      current_statement__ = 8;
      sigma_K = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      local_scalar_t__ sigma_L0 = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_L0 = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 10;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      {
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(Linf,
                         stan::model::rvalue(priors, "priors",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(priors_se, "priors_se",
                           stan::model::index_uni(1))));
        current_statement__ = 16;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(k, 0,
                         stan::model::rvalue(priors, "priors",
                           stan::model::index_uni(3))));
        current_statement__ = 17;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(L0,
                         stan::model::rvalue(priors, "priors",
                           stan::model::index_uni(2)),
                         stan::model::rvalue(priors_se, "priors_se",
                           stan::model::index_uni(2))));
        current_statement__ = 18;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(L_inf_j, Linf,
                         sigma_L_inf));
        current_statement__ = 19;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(K_j, k, sigma_K));
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(L0_j, L0, sigma_L0));
        current_statement__ = 21;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(sigma_L_inf, 0,
                         stan::model::rvalue(priors, "priors",
                           stan::model::index_uni(5))));
        current_statement__ = 22;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(sigma_K, 0,
                         stan::model::rvalue(priors, "priors",
                           stan::model::index_uni(7))));
        current_statement__ = 23;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(sigma_L0, 0,
                         stan::model::rvalue(priors, "priors",
                           stan::model::index_uni(6))));
        current_statement__ = 24;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(sigma, 0,
                         stan::model::rvalue(priors, "priors",
                           stan::model::index_uni(4))));
        current_statement__ = 27;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 25;
          lp_accum__.add(stan::math::normal_lpdf<false>(
                           stan::model::rvalue(length, "length",
                             stan::model::index_uni(i)),
                           (stan::model::rvalue(L_inf_j, "L_inf_j",
                              stan::model::index_uni(
                                stan::model::rvalue(individual, "individual",
                                  stan::model::index_uni(i)))) -
                           ((stan::model::rvalue(L_inf_j, "L_inf_j",
                               stan::model::index_uni(
                                 stan::model::rvalue(individual,
                                   "individual", stan::model::index_uni(i))))
                           -
                           stan::model::rvalue(L0_j, "L0_j",
                             stan::model::index_uni(
                               stan::model::rvalue(individual, "individual",
                                 stan::model::index_uni(i))))) *
                           stan::math::exp(
                             (-stan::model::rvalue(K_j, "K_j",
                                 stan::model::index_uni(
                                   stan::model::rvalue(individual,
                                     "individual", stan::model::index_uni(i))))
                             *
                             stan::model::rvalue(age, "age",
                               stan::model::index_uni(i)))))), sigma));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_Ranef_VB_stan_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double Linf = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      Linf = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      double k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      k = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
            lp__);
      double L0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      L0 = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double,-1,1> L_inf_j =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      L_inf_j = in__.template read_constrain_lb<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                  J);
      Eigen::Matrix<double,-1,1> K_j =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      K_j = in__.template read_constrain_lb<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, J);
      Eigen::Matrix<double,-1,1> L0_j =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      L0_j = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      double sigma_L_inf = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      sigma_L_inf = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      double sigma_K = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      sigma_K = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      double sigma_L0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 9;
      sigma_L0 = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 10;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      out__.write(Linf);
      out__.write(k);
      out__.write(L0);
      out__.write(L_inf_j);
      out__.write(K_j);
      out__.write(L0_j);
      out__.write(sigma_L_inf);
      out__.write(sigma_K);
      out__.write(sigma_L0);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 14;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 12;
        stan::model::assign(log_lik,
          stan::math::normal_lpdf<false>(
            stan::model::rvalue(length, "length", stan::model::index_uni(i)),
            (stan::model::rvalue(L_inf_j, "L_inf_j",
               stan::model::index_uni(
                 stan::model::rvalue(individual, "individual",
                   stan::model::index_uni(i)))) -
            ((stan::model::rvalue(L_inf_j, "L_inf_j",
                stan::model::index_uni(
                  stan::model::rvalue(individual, "individual",
                    stan::model::index_uni(i)))) -
            stan::model::rvalue(L0_j, "L0_j",
              stan::model::index_uni(
                stan::model::rvalue(individual, "individual",
                  stan::model::index_uni(i))))) *
            stan::math::exp(
              (-stan::model::rvalue(K_j, "K_j",
                  stan::model::index_uni(
                    stan::model::rvalue(individual, "individual",
                      stan::model::index_uni(i)))) *
              stan::model::rvalue(age, "age", stan::model::index_uni(i)))))),
            sigma), "assigning variable log_lik", stan::model::index_uni(i));
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ Linf = DUMMY_VAR__;
      current_statement__ = 1;
      Linf = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, Linf);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 2;
      k = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, k);
      local_scalar_t__ L0 = DUMMY_VAR__;
      current_statement__ = 3;
      L0 = in__.read<local_scalar_t__>();
      out__.write(L0);
      Eigen::Matrix<local_scalar_t__,-1,1> L_inf_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(L_inf_j,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable L_inf_j");
      out__.write_free_lb(0, L_inf_j);
      Eigen::Matrix<local_scalar_t__,-1,1> K_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(K_j,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable K_j");
      out__.write_free_lb(0, K_j);
      Eigen::Matrix<local_scalar_t__,-1,1> L0_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(L0_j,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable L0_j");
      out__.write(L0_j);
      local_scalar_t__ sigma_L_inf = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_L_inf = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_L_inf);
      local_scalar_t__ sigma_K = DUMMY_VAR__;
      current_statement__ = 8;
      sigma_K = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_K);
      local_scalar_t__ sigma_L0 = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_L0 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_L0);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 10;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "Linf", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "k", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "L0", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "L_inf_j",
        "double", std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "K_j", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "L0_j", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "sigma_L_inf",
        "double", std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "sigma_K",
        "double", std::vector<size_t>{});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "sigma_L0",
        "double", std::vector<size_t>{});
      current_statement__ = 10;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ Linf = DUMMY_VAR__;
      current_statement__ = 1;
      Linf = context__.vals_r("Linf")[(1 - 1)];
      out__.write_free_lb(0, Linf);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 2;
      k = context__.vals_r("k")[(1 - 1)];
      out__.write_free_lb(0, k);
      local_scalar_t__ L0 = DUMMY_VAR__;
      current_statement__ = 3;
      L0 = context__.vals_r("L0")[(1 - 1)];
      out__.write(L0);
      Eigen::Matrix<local_scalar_t__,-1,1> L_inf_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> L_inf_j_flat__;
        current_statement__ = 4;
        L_inf_j_flat__ = context__.vals_r("L_inf_j");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(L_inf_j, L_inf_j_flat__[(pos__ - 1)],
            "assigning variable L_inf_j", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, L_inf_j);
      Eigen::Matrix<local_scalar_t__,-1,1> K_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> K_j_flat__;
        current_statement__ = 5;
        K_j_flat__ = context__.vals_r("K_j");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(K_j, K_j_flat__[(pos__ - 1)],
            "assigning variable K_j", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, K_j);
      Eigen::Matrix<local_scalar_t__,-1,1> L0_j =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> L0_j_flat__;
        current_statement__ = 6;
        L0_j_flat__ = context__.vals_r("L0_j");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 6;
          stan::model::assign(L0_j, L0_j_flat__[(pos__ - 1)],
            "assigning variable L0_j", stan::model::index_uni(sym1__));
          current_statement__ = 6;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(L0_j);
      local_scalar_t__ sigma_L_inf = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_L_inf = context__.vals_r("sigma_L_inf")[(1 - 1)];
      out__.write_free_lb(0, sigma_L_inf);
      local_scalar_t__ sigma_K = DUMMY_VAR__;
      current_statement__ = 8;
      sigma_K = context__.vals_r("sigma_K")[(1 - 1)];
      out__.write_free_lb(0, sigma_K);
      local_scalar_t__ sigma_L0 = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_L0 = context__.vals_r("sigma_L0")[(1 - 1)];
      out__.write_free_lb(0, sigma_L0);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 10;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"Linf", "k", "L0", "L_inf_j", "K_j",
                "L0_j", "sigma_L_inf", "sigma_K", "sigma_L0", "sigma"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "Linf");
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "L0");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "L_inf_j" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "K_j" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "L0_j" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_L_inf");
    param_names__.emplace_back(std::string() + "sigma_K");
    param_names__.emplace_back(std::string() + "sigma_L0");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "Linf");
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "L0");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "L_inf_j" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "K_j" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "L0_j" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_L_inf");
    param_names__.emplace_back(std::string() + "sigma_K");
    param_names__.emplace_back(std::string() + "sigma_L0");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"Linf\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"L0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"L_inf_j\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"K_j\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"L0_j\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"sigma_L_inf\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_K\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_L0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"Linf\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"L0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"L_inf_j\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"K_j\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"L0_j\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"sigma_L_inf\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_K\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_L0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((((1 + 1) + 1) + J) + J) + J) + 1) + 1)
      + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((((1 + 1) + 1) + J) + J) + J) + 1) + 1)
      + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_Ranef_VB_stan_model_namespace::model_Ranef_VB_stan_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_Ranef_VB_stan_model_namespace::profiles__;
}
#endif
#endif
